### PR TITLE
Add authentication

### PR DESCRIPTION
**Pull request by dannyslocum**
Added an option to use your espn username and password instead of searching for the swid and s2 variables. Good work on this!

### CODE REVIEW

**Comment by dannyslocum** [comment]
Another suggestion would be to make the 'year' variable in the 'League' class optional. I did this before by making a self.current_year =str(int(datetime.now().year)). I can make another pull request for this if you're interested.

**Comment by cwendt94** [comment]
This is awesome! I didn't even think about looking into logging in via username and password. I will checkout the PR and try to get it in the next day or two.

For the year being optional ESPN still considers January and February being 2019. I and fine with adding year optional you would just need to take that into account.

**Comment by dannyslocum** [comment]
Yeah that makes sense. My fantasy leagues all end in December so I'm used to just ending it early. Should be pretty straight forward to factor those months in though.

**Comment by cwendt94** [comment]
Looks good!

**Pull request merged**
